Repository be15-4th-project/be15-4th-DAO-NBTI-front, pull requests merged in 2025-05, with the labels that each got.

#32 [init] 헤더 컴포넌트 생성
  be15-4th-dao-nbti-fe/src/components/layout/Header.vue
  be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue
Labels: feat

#35 Init : 각 분야별 아이콘 추가 및 사이트 로고 업로드
  be15-4th-dao-nbti-fe/src/assets/images/common_sense.png
  be15-4th-dao-nbti-fe/src/assets/images/images.txt
  be15-4th-dao-nbti-fe/src/assets/images/language_comprehension.png
  be15-4th-dao-nbti-fe/src/assets/images/logo.png
  be15-4th-dao-nbti-fe/src/assets/images/perceptual_reasoning.png
  be15-4th-dao-nbti-fe/src/assets/images/processing_speed.png
  be15-4th-dao-nbti-fe/src/assets/images/spatial_perception.png
  be15-4th-dao-nbti-fe/src/assets/images/work_memory.png
Labels: init

#34 feat : Modal 만들기
  be15-4th-dao-nbti-fe/src/components/common/BigModal.vue
  be15-4th-dao-nbti-fe/src/components/common/SmallModal.vue
Labels: feat

#36 feat: LayoutDefault 기초 뼈대 잡기(Header, Siderbar)
  .gitignore
  be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue
  be15-4th-dao-nbti-fe/src/components/layout/Sidebar.vue
  be15-4th-dao-nbti-fe/src/components/layout/sidebar/AdminSidebar.vue
  be15-4th-dao-nbti-fe/src/components/layout/sidebar/GeneralSidebar.vue
  be15-4th-dao-nbti-fe/src/features/admin/components/component.vue
Labels: feat

#39 refactor : 모달 내용 위치 수정 및 slot 추가
  be15-4th-dao-nbti-fe/src/components/common/BigModal.vue
  be15-4th-dao-nbti-fe/src/components/common/SmallModal.vue
Labels: refactor

#37 로그인, 토큰 리프레시, 로그아웃 기능 구현
  be15-4th-dao-nbti-fe/.env
  be15-4th-dao-nbti-fe/src/api/axios.js
  be15-4th-dao-nbti-fe/src/components/layout/Header.vue
  be15-4th-dao-nbti-fe/src/features/user/api.js
  be15-4th-dao-nbti-fe/src/features/user/components/BlueButton.vue
  be15-4th-dao-nbti-fe/src/features/user/components/LoginForm.vue
  be15-4th-dao-nbti-fe/src/features/user/components/UserInput.vue
  be15-4th-dao-nbti-fe/src/features/user/components/component.vue
  be15-4th-dao-nbti-fe/src/features/user/router.js
  be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue
  be15-4th-dao-nbti-fe/src/features/user/views/login.vue
  be15-4th-dao-nbti-fe/src/main.js
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: feat

#38 feat: 문제 목록 조회 페이지 구현
  be15-4th-dao-nbti-fe/src/components/layout/Sidebar.vue
  be15-4th-dao-nbti-fe/src/components/layout/sidebar/AdminSidebar.vue
  be15-4th-dao-nbti-fe/src/features/admin/api.js
  be15-4th-dao-nbti-fe/src/features/admin/router.js
  be15-4th-dao-nbti-fe/src/features/admin/views/ProblemSearchView.vue
  be15-4th-dao-nbti-fe/src/features/admin/views/UserListView.vue
  be15-4th-dao-nbti-fe/src/features/admin/views/view.vue
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: feat

#40 feat : 마이페이지 페이지 구현 (리펙토링 필요)
  be15-4th-dao-nbti-fe/package-lock.json
  be15-4th-dao-nbti-fe/package.json
  be15-4th-dao-nbti-fe/src/assets/images/objection.svg
  be15-4th-dao-nbti-fe/src/components/layout/Header.vue
  be15-4th-dao-nbti-fe/src/features/mypage/api.js
  be15-4th-dao-nbti-fe/src/features/mypage/components/LayoutMypage.vue
  be15-4th-dao-nbti-fe/src/features/mypage/components/LineChart.vue
  be15-4th-dao-nbti-fe/src/features/mypage/components/Pagination.vue
  be15-4th-dao-nbti-fe/src/features/mypage/components/RadarChart.vue
  be15-4th-dao-nbti-fe/src/features/mypage/components/ResultCard.vue
  be15-4th-dao-nbti-fe/src/features/mypage/components/Sidebar.vue
  be15-4th-dao-nbti-fe/src/features/mypage/components/component.vue
  be15-4th-dao-nbti-fe/src/features/mypage/router.js
  be15-4th-dao-nbti-fe/src/features/mypage/views/ObjectionListView.vue
  be15-4th-dao-nbti-fe/src/features/mypage/views/StudyDetailView.vue
  be15-4th-dao-nbti-fe/src/features/mypage/views/StudyListView.vue
  be15-4th-dao-nbti-fe/src/features/mypage/views/TestResultDetailView.vue
  be15-4th-dao-nbti-fe/src/features/mypage/views/TestResultListView.vue
  be15-4th-dao-nbti-fe/src/features/mypage/views/view.vue
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: feat

#44 feat : 학습 내역 목록 조회 api 연동
  be15-4th-dao-nbti-fe/env
  be15-4th-dao-nbti-fe/src/features/mypage/api.js
  be15-4th-dao-nbti-fe/src/features/mypage/views/StudyListView.vue
Labels: feat

#45 feat : 메인 페이지에 있는 검사 구현
  be15-4th-dao-nbti-fe/src/features/main/components/TestStart.vue
  be15-4th-dao-nbti-fe/src/features/main/views/MainView.vue
  be15-4th-dao-nbti-fe/src/features/test/api.js
  be15-4th-dao-nbti-fe/src/features/test/components/component.vue
  be15-4th-dao-nbti-fe/src/features/test/router.js
  be15-4th-dao-nbti-fe/src/features/test/views/view.vue
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: feat

#46 fix : TestView가 없어 발생하는 오류 해결을 위한 임시 뷰
  be15-4th-dao-nbti-fe/src/features/test/views/TestView.vue
Labels: fix

#49 feat: 이의 제기 목록 조회 페이지 구현
  be15-4th-dao-nbti-fe/src/components/layout/sidebar/AdminSidebar.vue
  be15-4th-dao-nbti-fe/src/features/admin/router.js
  be15-4th-dao-nbti-fe/src/features/admin/views/ObjectionDetailsView.vue
  be15-4th-dao-nbti-fe/src/features/admin/views/ObjectionSearchView.vue
Labels: feat

#48 feat: 메인 페이지 학습 리스트 컴포넌트 구현
  be15-4th-dao-nbti-fe/.gitignore
  be15-4th-dao-nbti-fe/env
  be15-4th-dao-nbti-fe/src/components/common/DifficultyModal.vue
  be15-4th-dao-nbti-fe/src/components/common/LoginRequiredModal.vue
  be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue
  be15-4th-dao-nbti-fe/src/components/layout/Sidebar.vue
  be15-4th-dao-nbti-fe/src/features/main/components/StudyCard.vue
  be15-4th-dao-nbti-fe/src/features/main/components/StudyCategoryListFrame.vue
  be15-4th-dao-nbti-fe/src/features/main/components/TestStart.vue
  be15-4th-dao-nbti-fe/src/features/main/views/MainView.vue
  be15-4th-dao-nbti-fe/src/features/main/views/view.vue
  be15-4th-dao-nbti-fe/src/features/study/router.js
  be15-4th-dao-nbti-fe/src/features/study/views/StudyResultView.vue
  be15-4th-dao-nbti-fe/src/features/study/views/view.vue
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: feat

#50 fix: index.js - testRoutes 누락 해결
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: fix

#55 feat: 회원 목록 조회 페이지 구현
  be15-4th-dao-nbti-fe/src/features/admin/api.js
  be15-4th-dao-nbti-fe/src/features/admin/components/PagingBar.vue
  be15-4th-dao-nbti-fe/src/features/admin/views/UserListView.vue
  be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue
Labels: feat

#59 feat: 검사 결과 조회 페이지 구현
  be15-4th-dao-nbti-fe/src/features/admin/api.js
  be15-4th-dao-nbti-fe/src/features/admin/router.js
  be15-4th-dao-nbti-fe/src/features/admin/views/TestListView.vue
Labels: feat

#57 feat: 학습 진행 및 학습 결과 페이지 구현
  be15-4th-dao-nbti-fe/src/features/main/components/StudyCategoryListFrame.vue
  be15-4th-dao-nbti-fe/src/features/study/api.js
  be15-4th-dao-nbti-fe/src/features/study/components/QuestionDetail.vue
  be15-4th-dao-nbti-fe/src/features/study/components/QuestionOptions.vue
  be15-4th-dao-nbti-fe/src/features/study/components/ResultSummary.vue
  be15-4th-dao-nbti-fe/src/features/study/components/component.vue
  be15-4th-dao-nbti-fe/src/features/study/router.js
  be15-4th-dao-nbti-fe/src/features/study/views/StudyResultView.vue
  be15-4th-dao-nbti-fe/src/features/study/views/StudyView.vue
Labels: feat

#61 refactor : 검사 결과 목록조회 점수 카드 누락 수정
  be15-4th-dao-nbti-fe/src/api/axios.js
  be15-4th-dao-nbti-fe/src/features/mypage/views/TestResultListView.vue
Labels: refactor

#54 feat : 검사 진행 기능 페이지 구현 및 api 연동
  be15-4th-dao-nbti-fe/src/features/test/api.js
  be15-4th-dao-nbti-fe/src/features/test/router.js
  be15-4th-dao-nbti-fe/src/features/test/views/TestView.vue
Labels: feat

#66 refactor: 헤더 및 레이아웃 수정
  be15-4th-dao-nbti-fe/src/components/layout/Header.vue
  be15-4th-dao-nbti-fe/src/components/layout/Sidebar.vue
  be15-4th-dao-nbti-fe/src/components/layout/sidebar/GeneralSidebar.vue
  be15-4th-dao-nbti-fe/src/features/admin/components/AdminLayout.vue
  be15-4th-dao-nbti-fe/src/features/admin/components/AdminSidebar.vue
  be15-4th-dao-nbti-fe/src/features/admin/router.js
Labels: refactor

#67 feat: 회원 탈퇴 기능 구현
  be15-4th-dao-nbti-fe/src/components/layout/Header.vue
  be15-4th-dao-nbti-fe/src/features/mypage/api.js
  be15-4th-dao-nbti-fe/src/features/mypage/views/UserInfoView.vue
Labels: feat, fix

#68 fix : 잘못된 api 경로 수정
  be15-4th-dao-nbti-fe/src/features/test/api.js
  be15-4th-dao-nbti-fe/src/features/test/views/TestResultView.vue
Labels: fix

#65 refactor: 작업 기억 카테고리 문제들에 대한 요구사항 반영(숫자 한 개씩 화면에 출력)
  be15-4th-dao-nbti-fe/src/features/study/views/StudyView.vue
Labels: refactor

#70 refactor : 마이페이지 접근 권한 제한
  be15-4th-dao-nbti-fe/src/features/mypage/router.js
  be15-4th-dao-nbti-fe/src/features/mypage/views/StudyDetailView.vue
  be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: refactor

#72 refactor: 관리자 이의 제기 조회 페이지 수정
  be15-4th-dao-nbti-fe/src/features/admin/views/ObjectionDetailsView.vue
  be15-4th-dao-nbti-fe/src/features/admin/views/ObjectionSearchView.vue
Labels: refactor

#75 refactor: 헤더 레이아웃 수정
  be15-4th-dao-nbti-fe/src/components/layout/Header.vue
Labels: refactor

#71 [refactor] 학습 문제 로드시 input 자동 포커스 기능 추가
  be15-4th-dao-nbti-fe/src/features/study/views/StudyView.vue
Labels: refactor

#74 refactor : 브라우저 탭의 홈페이지 이름 수정
  be15-4th-dao-nbti-fe/index.html
Labels: refactor

#79 refactor: 문제 답이 여러 칸에 걸쳐있는 경우 placeholder 추가, 학습 시작 전 안내 모달 추가
  be15-4th-dao-nbti-fe/src/features/main/components/StudyCategoryListFrame.vue
  be15-4th-dao-nbti-fe/src/features/study/views/StudyView.vue
Labels: refactor

#80 fix: 학습 시작 전 안내 모달 닫기 버튼 동작 오류 수정
  be15-4th-dao-nbti-fe/src/features/main/components/StudyCategoryListFrame.vue
Labels: fix

#84 [init] footer 생성
  be15-4th-dao-nbti-fe/src/components/layout/Footer.vue
  be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue
Labels: init

#87 init : 사용자 프로필 추가 및 성별 한글 변환
  be15-4th-dao-nbti-fe/src/components/layout/Footer.vue
  be15-4th-dao-nbti-fe/src/features/mypage/views/UserInfoView.vue
Labels: init

#91 refactor : 로그인 성공 시 모달창 뜨지 않게 수정
  be15-4th-dao-nbti-fe/src/features/user/components/LoginForm.vue
  be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue
Labels: refactor

#94 refactor : 이의제기 상세조회의 관리자 처리 사유 확인
  be15-4th-dao-nbti-fe/src/features/mypage/views/ObjectionListView.vue
Labels: refactor

#93 [fix] 회원이 관리자 페이지에 접근 가능한 문제 수정
  be15-4th-dao-nbti-fe/src/features/admin/router.js
  be15-4th-dao-nbti-fe/src/router/index.js
Labels: fix

#101 fix: axios 기본 경로 수정
  be15-4th-dao-nbti-fe/src/api/axios.js
Labels: fix

#102 fix: 앱 로드 시점 이전에 window.env에 axios 기본 경로 변수 등록하기
  be15-4th-dao-nbti-fe/index.html
Labels: fix
